"""added email to eser

Revision ID: 3e1a35450427
Revises: ab12da1bba74
Create Date: 2022-02-16 22:34:32.691046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1a35450427'
down_revision = 'ab12da1bba74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'email')
    # ### end Alembic commands ###
